name: nixo
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  dio: ^4.0.6
  equatable: ^2.0.3
  firebase_auth: ^3.10.0
  firebase_core: ^1.23.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_localizations:
    sdk: flutter
  flutter_spinkit: ^5.1.0
  flutter_advanced_drawer: ^1.3.2
  fluttertoast: ^8.0.9
  get_it: ^7.2.0
  http: ^0.13.4
  internet_connection_checker: ^0.0.1+4
  introduction_screen: ^3.0.2
  persistent_bottom_nav_bar: ^5.0.2
  shared_preferences: ^2.0.15
  circular_countdown_timer: ^0.2.2
  
  calendar_timeline: ^1.0.5
  flutter_slidable: ^2.0.0

dev_dependencies:
  change_app_package_name: ^1.1.0

  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/images/add.png
    - assets/images/addfile.png
    - assets/images/calendar.png
    - assets/images/checkIcon.png
    - assets/images/cleardarkIcon.png
    - assets/images/clearxIcon.png
    - assets/images/errorIcon.png
    - assets/images/facebook.png
    - assets/images/files.png
    - assets/images/Google.png
    - assets/images/home.png
    - assets/images/items.png
    - assets/images/logo.png
    - assets/images/notifications.png
    - assets/images/obtulus.png
    - assets/images/onboardbcgr.png
    - assets/images/onBoarding1.png
    - assets/images/onBoarding2.png
    - assets/images/onBoarding3.png
    - assets/images/onBoarding4.png
    - assets/images/pomodoro.png
    - assets/images/search.png
    - assets/images/settings.png
    - assets/images/sun.png
    - assets/images/tasks.png
    - assets/images/authbackground.png
    - assets/images/drawer_bcr.png
    - assets/images/overviewCard.png

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-ExtraBold.ttf
          weight: 800

        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700

        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600

        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500

        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 400

        - asset: assets/fonts/Montserrat-Light.ttf
          weight: 300
