name: nixo
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  dio: ^4.0.6
  equatable: ^2.0.3
  firebase_auth: ^3.10.0
  firebase_core: ^1.23.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_localizations:
    sdk: flutter
  flutter_spinkit: ^5.1.0
  fluttertoast: ^8.0.9
  get: ^4.6.5
  get_it: ^7.2.0
  http: ^0.13.4
  internet_connection_checker: ^0.0.1+4
  shared_preferences: ^2.0.15

dev_dependencies:
  change_app_package_name: ^1.1.0

  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-ExtraBold.ttf
          weight: 800

        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700

        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600

        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500

        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 400

        - asset: assets/fonts/Montserrat-Light.ttf
          weight: 300
