// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4idMeRIjNa9gAWPIRH0R5pFzz62trqfU',
    appId: '1:802903971281:web:918aa64e3f84c828fdbcf0',
    messagingSenderId: '802903971281',
    projectId: 'nixo-1c978',
    authDomain: 'nixo-1c978.firebaseapp.com',
    storageBucket: 'nixo-1c978.appspot.com',
    measurementId: 'G-SPBWLVWJ20',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkUbSyUgkoYA8nQvo8WEoaNQCFWfueiqY',
    appId: '1:802903971281:android:ff0564d857a1eba3fdbcf0',
    messagingSenderId: '802903971281',
    projectId: 'nixo-1c978',
    storageBucket: 'nixo-1c978.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBk_PJIIfNo5hLuax9UGy3ZRAZjpArtdvQ',
    appId: '1:802903971281:ios:4a382bcf51162c78fdbcf0',
    messagingSenderId: '802903971281',
    projectId: 'nixo-1c978',
    storageBucket: 'nixo-1c978.appspot.com',
    iosClientId: '802903971281-k4q3h62qir18btcivuuoh32dufkudc2c.apps.googleusercontent.com',
    iosBundleId: 'com.obtulus.nixo.nixo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBk_PJIIfNo5hLuax9UGy3ZRAZjpArtdvQ',
    appId: '1:802903971281:ios:4a382bcf51162c78fdbcf0',
    messagingSenderId: '802903971281',
    projectId: 'nixo-1c978',
    storageBucket: 'nixo-1c978.appspot.com',
    iosClientId: '802903971281-k4q3h62qir18btcivuuoh32dufkudc2c.apps.googleusercontent.com',
    iosBundleId: 'com.obtulus.nixo.nixo',
  );
}
